name: ocicrypt-rs build
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ocicrypt-rs/**'
      - '.github/workflows/ocicrypt_rs_build.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'ocicrypt-rs/**'
      - '.github/workflows/ocicrypt_rs_build.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  create:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: github.event_name != 'push'
    name: Check
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.76.0

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install tonic's protoc dependencies
        run: |
          sudo apt install -y protobuf-compiler libprotobuf-dev

      # TODO: add coverage  for keywrap-jwe
      # Now it is deleted because it is not stable in 1.76.0
      - name: Run cargo build (ttrpc + ring)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p ocicrypt-rs --no-default-features --features=block-cipher-ring,keywrap-keyprovider

      - name: Run cargo test (ttrpc + ring)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ocicrypt-rs --no-default-features --features=block-cipher-ring,keywrap-keyprovider

      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -p ocicrypt-rs -- --check

      - name: Run rust lint check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p ocicrypt-rs --no-default-features --features=block-cipher-ring,keywrap-keyprovider
